installation/urls.py
from django.urls import path
from django import views
from . import views
from .views import *
urlpatterns=[
   path('',views.installation,name='installation'),
   path('installation/start',InstallationView.as_view(),name='installation start')
]

manager/urls.py
from django.urls import path
from django import views
from . import views
from .views import *
from django.contrib.auth import views as auth_views
urlpatterns=[
    path('',Home.as_view(),name='dashboard'),
    path('reviewmodel',views.serialize_model_data,name='review_model'),
    path('subscribe',views.subscribe,name='subscribe'),
    path('accounts/login',Login.as_view(),name='login'),
    path('accounts/register',Register.as_view(),name='register'),
    path('accounts/logout',views.UserLogout,name='logout'),
    path('accounts/activate',views.account_activate,name='account activate'),
    path('accounts/activate/<uidb64>/<token>', views.acc_acctivate,name='activate'),

    path('accounts/reset/password',auth_views.PasswordResetView.as_view(form_class=User_resetPassword,template_name='manager/password_reset.html'),{'site_name':'devme','title':'Password reset'},name='password_reset'),
    path('accounts/reset/password/done',auth_views.PasswordResetDoneView.as_view(template_name='manager/password_reset_done.html'),name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='manager/password_reset_confirm.html'),name='password_reset_confirm'),
    path('reset/password/success',auth_views.PasswordResetCompleteView.as_view(template_name='manager/password_reset_complete.html'),name='password_reset_complete'),

    path('<username>', Profile.as_view(),name='profile'),
    path('password/change',views.passwordChange,name='password change'),
    path('edit/social/links',views.edit_social_link,name='edit social link'),
    path('change/profile/pic',views.profilePic,name='profile pic'),


    path('site/users',views.users,name='users'),
    path('add/users',AddUser.as_view(),name='add users'),
    path('edit/users/<id>',EditUser.as_view(),name='edit user'),
    path('delete/users/<id>',views.deleteUser,name='delete user'),

    path('site/settings',EditSite.as_view(),name='site settings'),
    path('site/contact',views.siteContact,name='site contact'),
    path('site/working/days',views.siteWorking,name='site working days'),
    path('site/social/links',views.siteSocial,name='site social links'),
    path('site/chats',views.chats,name='chats'),

    path('site/blogs',views.blogs,name='blogs'),
    path('site/blogs/details',blogsDetails.as_view(),name='blogs details'),



    path('site/projects',views.projects,name='projects'),
    path('add/project',AddProject.as_view(),name='add project'),
    path('edit/project/<id>',EditProject.as_view(),name='edit project'),
    path('delete/project/<id>',views.deleteProject,name='delete project'),

    path('designs/and/clients',views.designs,name='designs'),
    path('add/skill',AddSkill.as_view(),name='add skill'),
    path('edit/skill/<id>',EditSkill.as_view(),name='edit skill'),
    path('delete/skill/<id>',views.deleteSkill,name='delete skill'),


    path('site/reviews',views.reviews,name='reviews'),
    path('add/review',AddReview.as_view(),name='add review'),
    path('edit/review/<id>',EditReview.as_view(),name='edit review'),
    path('delete/review/<id>',views.deleteReview,name='delete review'),

]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('installation/',include('installation.urls')),
    path('', include('manager.urls')),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]


urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

handler400 ='errors.views.error_400'
handler403 ='errors.views.error_403'
handler404 ='errors.views.error_404'
handler500='errors.views.error_500'

installation/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
from django.utils.timezone import now
import environ
env=environ.Env()
environ.Env.read_env()

# Create your models here.

class SiteConstants(models.Model):
    user=models.OneToOneField(User,primary_key=True,on_delete=models.CASCADE)
    site_name=models.CharField(null=True,blank=True,max_length=100,default=env('SITE_NAME'))
    site_email=models.CharField(null=True,blank=True,max_length=100,default=env('SITE_EMAIL'))
    site_email2=models.CharField(null=True,blank=True,max_length=100,default=env('SITE_EMAIL2'))
    theme_color=models.CharField(null=True,blank=True,max_length=100,default=env('THEME_COLOR'))
    site_url=models.URLField(null=True,blank=True,default=env('SITE_URL'))
    cv_file=models.FileField(null=True,blank=True,upload_to='docs/',default="docs/kevin_kibebe_cv.pdf")
    description=models.TextField(null=True,blank=True,default=env('SITE_DESCRIPTION'))
    key_words=models.TextField(null=True,blank=True,default=env('SITE_KEYWORDS'))
    address=models.CharField(null=True,blank=True,max_length=250,default=env('SITE_ADDRESS'))
    clients=models.IntegerField(default=0,blank=True,null=True)
    completed_projects=models.IntegerField(default=0,blank=True,null=True)
    ongoing_projects=models.IntegerField(default=0,blank=True,null=True)
    client_satisfactory=models.IntegerField(default=0,blank=True,null=True)
    location=models.CharField(null=True,blank=True,max_length=250,default=env('SITE_LOCATION'))
    phone=PhoneNumberField(null=True,blank=True,verbose_name='phone',unique=False,default=env('SITE_PHONE1'))
    phone2=PhoneNumberField(null=True,blank=True,verbose_name='phone2',unique=False,default=env('SITE_PHONE2'))
    working_days=models.CharField(null=True,blank=True,max_length=250,default="mon-fri")
    site_content=models.CharField(null=True,blank=True,max_length=250)
    working_hours=models.CharField(null=True,blank=True,max_length=250,default="8am-10pm")
    closed_days=models.CharField(null=True,blank=True,max_length=250,default="sun")
    special_days=models.CharField(null=True,blank=True,max_length=250,default="sat & holidays")
    special_hours=models.CharField(null=True,blank=True,max_length=250,default="sat & holidays")
    facebook=models.URLField(null=True,blank=True,max_length=250,default=env('FACEBOOK_LINK'))
    twitter=models.URLField(null=True,blank=True,max_length=250,default=env('TWITTER_LINK'))
    instagram=models.URLField(null=True,blank=True,max_length=250,default=env('INSTAGRAM_LINK'))
    whatsapp=models.URLField(null=True,blank=True,max_length=250,default=env('WHATSAPP_LINK'))
    linkedin=models.URLField(null=True,blank=True,max_length=250,default=env('LINKEDIN_LINK'))
    youtube=models.URLField(null=True,blank=True,max_length=250,default=env('YOUTUBE_LINK'))
    favicon=models.ImageField(null=True,blank=True,upload_to='logos/',default="logos/favicon.ico")
    icon_180=models.ImageField(null=True,blank=True,upload_to='logos/',default="favicon-180x180.png")
    icon_32=models.ImageField(null=True,blank=True,upload_to='logos/',default="favicon-32x32.png")
    icon_16=models.ImageField(null=True,blank=True,upload_to='logos/',default="favicon-16x16.png")
    created_on=models.DateTimeField(default=now)
    class Meta:
        db_table='site_constants'
        verbose_name_plural='site_constants'
    def __str__(self):
        return f'{self.user.username} site constants'

installation/forms.py
from django import forms
from django.contrib.auth.models import User
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email
from manager.models import ExtendedAuthUser
from manager.models import ExtendedAdmin
from .models import SiteConstants
#new admin register form
class AdminRegisterForm(UserCreationForm):
    first_name=forms.CharField(widget=forms.TextInput(attrs={'style':'text-transform:lowercase;','class':'form-control','aria-label':'first_name'}),error_messages={'required':'First is required'})
    last_name=forms.CharField(widget=forms.TextInput(attrs={'style':'text-transform:lowercase;','class':'form-control','aria-label':'last_name'}),error_messages={'required':'Last name is required'})
    username=forms.CharField(widget=forms.TextInput(attrs={'style':'text-transform:lowercase;','class':'form-control','aria-label':'username'}),error_messages={'required':'Username is required'})
    email=forms.EmailField(widget=forms.EmailInput(attrs={'style':'text-transform:lowercase;','class':'form-control','aria-label':'email'}),error_messages={'required':'Email address is required'})
    password1=forms.CharField(widget=forms.PasswordInput(attrs={'style':'text-transform:lowercase;','class':'form-control','id':"password",'aria-label':'password1'}),error_messages={'required':'Password is required'})
    password2=forms.CharField(widget=forms.PasswordInput(attrs={'style':'text-transform:lowercase;','class':'form-control','aria-label':'password2'}),error_messages={'required':'Confirm password is required'})
    class Meta:
        model=User
        fields=['first_name','last_name','email','username','password1','password2']


    def clean_first_name(self):
        first_name=self.cleaned_data['first_name']
        if not str(first_name).isalpha():
                raise forms.ValidationError('only characters are allowed.')
        return first_name
    
    def clean_last_name(self):
        last_name=self.cleaned_data['last_name']
        if not str(last_name).isalpha():
                raise forms.ValidationError('only characters are allowed.')
        return last_name
    def clean_email(self):
        email=self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
                raise forms.ValidationError('A user with this email already exists.')
        try:
            validate_email(email)
        except ValidationError as e:
            raise forms.ValidationError('Invalid email address.')
        return email

    def clean_username(self):
        username=self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
                raise forms.ValidationError('A user with this username already exists.')
        return username


class ExtendedAdminRegisterForm(forms.ModelForm):
    phone=PhoneNumberField(widget=PhoneNumberPrefixWidget(attrs={'class':'form-control','aria-label':'phone'},initial='KE'),error_messages={'required':'Phone number is required'})

    class Meta:
        model=ExtendedAuthUser
        fields=['phone']


class SiteConfigForm(forms.ModelForm):
    site_name=forms.CharField(widget=forms.TextInput(attrs={'style':'text-transform:capitalize;','class':'form-control','aria-label':'site_name'}),error_messages={'required':'Site name is required'})
    site_url=forms.URLField(widget=forms.URLInput(attrs={'style':'text-transform:lowercase;','placeholder':'eg example.com','class':'form-control','aria-label':'site_url'}),error_messages={'required':'Site url is required'})
    class Meta:
        model=SiteConstants
        fields=['site_name','site_url']

    def clean_site_url(self):
        site_url=self.cleaned_data.get('site_url')
        if site_url.find('http://'):
            return site_url.replace('http://','')
        elif site_url.find('https://'):
            return site_url.replace('https://','')
        else:
            return site_url

class SubForm(forms.ModelForm):
    main=forms.BooleanField(widget=forms.CheckboxInput(attrs={'class':'form-check-input','aria-label':'main','checked':True}),error_messages={'required':'This field is required'})
    class Meta:
        model=ExtendedAdmin
        fields=['main']

installation/views.py
from django.shortcuts import render
from .forms import *
from django.views.generic import View
from django.http import JsonResponse
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from manager.tokens import create_token
from django.contrib.sites.shortcuts import get_current_site
from  django.contrib.auth.models import Group
from manager.addons import send_email,getSiteData,sociallinks
from django.core.cache import cache
from django.contrib.sites.models import Site
# Create your views here.

def installation(request):
	return render(request,'installation/installation.html',{'title':'Site Installation | Powered By DevMe'})



class InstallationView(View):
	def get(self,request, *args, **kwargs):
		userform=AdminRegisterForm()
		extendedForm=ExtendedAdminRegisterForm()
		siteconstantform=SiteConfigForm()
		main=SubForm()
		count=ExtendedAdmin.objects.count()
		data={'userform':userform,'extendedForm':extendedForm,'siteconstantform':siteconstantform,'main':main,'count':count}	
		return render(request,'installation/installation_user_register.html',context=data)
	def post(self,request, *args, **kwargs):
		userform=AdminRegisterForm(request.POST or None)
		extendedForm=ExtendedAdminRegisterForm(request.POST or None)
		siteconstantform=SiteConfigForm(request.POST or None)
		main=SubForm(request.POST or None)
		if userform.is_valid() and extendedForm.is_valid() and siteconstantform.is_valid() and main.is_valid():
			user=userform.save(commit=False)
			user.is_superuser=True
			user.is_staff=True
			user.save()
			if not Group.objects.filter(name='admins').exists():
				group=Group.objects.create(name='admins')
				group.user_set.add(user)
				group.save()
			else:
				group=Group.objects.get(name__icontains='admins')
				group.user_set.add(user)
				group.save()
			extended=extendedForm.save(commit=False)
			extended.user=user
			extended.initials=userform.cleaned_data.get('first_name')[0].upper()+userform.cleaned_data.get('last_name')[0].upper()
			extended.social_links=sociallinks()
			extended.role='Admin'
			extended.save()
			lastdata=siteconstantform.save(commit=False)
			lastdata.user=user
			lastdata.save()
			admindata=main.save(commit=False)
			admindata.user=user
			admindata.is_installed=True
			Site.objects.create(name=siteconstantform.cleaned_data.get('site_name'),domain=siteconstantform.cleaned_data.get('site_url'))
			admindata.save()
			return JsonResponse({'valid':True,'message':'data saved'},content_type='application/json')
		else:
			return JsonResponse({'valid':False,'main_errors':main.errors,'userform_errors':userform.errors,'extendedForm_errors':extendedForm.errors,'siteconstantform_errors':siteconstantform.errors},content_type='application/json')

templates/installation/installation.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">
<head>
    <title>{{title}}</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Site installation">
    <meta name="author" content="DevMe">
    <meta name="theme-color" content="#39f">
    <meta name="msapplication-navbutton-color" content="#39f">
    <meta name="apple-mobile-web-app-status-bar-style" content="#39f">
    <meta name="keywords" content="site installation,web setup">
    <meta http-equiv="Content-type" content="text/html;charset:utf-8">
    <meta property="og:type" content="website"> 
    <meta property="twitter:site" content="https://twitter.com/Kevin36285655">
    <meta property="twitter:title" content="@Kevin36285655">
    <meta property="twitter:image" content="https://pbs.twimg.com/profile_images/1385307847542640644/zZrPhJUm_normal.jpg">
    <meta property="twitter:description" content="Follow us on twitter for more infomation and amaizing deals.">
    <meta property="twitter:text:title" content="web designs,development,setup and installation">
    <meta property="og:title" content="DevMe | Web installation">
    <meta property="og:locale" content="en_US">
    <meta property="og:description" content="Site installation">
    <meta property="og:image" content="{% static 'installation/assets/images/favicon.ico' %}">
    <meta name="apple-mobile-web-app-title" content="DevMe">
    <meta name="application-name" content="DevMe">
    <meta name="msapplication-TileColor" content="#39f">
    <meta name="msapplication-config" content="{% static 'installation/assets/images/icons/browserconfig.xml' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'installation/assets/images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'installation/assets/css/plugins.css' %}">
    
    <!-- Main Style CSS -->
    <link rel="stylesheet" href="{% static 'installation/assets/css/plugins/owl-carousel/owl.carousel.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css" integrity="sha512-OTcub78R3msOCtY3Tc6FzeDJ8N9qvQn1Ph49ou13xgA9VsH9+LRxoFU6EqLhW4+PKRfU+/HReXmSZXHEkpYoOA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'installation/assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'installation/assets/css/custom.css' %}">
    <style>
      
    </style>
</head>

<body>

    <!--slider area start-->
    <section class="slider_section d-flex align-items-center" data-bgimg="{% static 'installation/assets/images/slider3.jpg' %}" style="height:100vh;margin-bottom:0 !important;">
        <div class="slider_area owl-carousel">
            <div class="single_slider d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6 col-md-6">
                            <div class="slider_content">
                                <img src="{% static 'installation/assets/images/1.png' %}" alt="">
                            </div>
                        </div>
                        <div class="col-xl-6 col-md-6">
                            <div class="slider_content">
                                <h1>Hello,</h1>
                                <h2>Welcome To Website Setup Wizard.</h2>
                                <p>Offering best web solution services.Begin setup</p>
                                <a class="button button1" href="#">next</a>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="single_slider d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6 col-md-6">
                            <div class="slider_content">
                                <img src="{% static 'installation/assets/images/2.png' %}" alt="slider image">
                            </div>
                        </div>
                        <div class="col-xl-6 col-md-6">
                            <div class="slider_content">
                                <h1>Accept Terms And Conditions.</h1>
                                <h2>100% Flexible</h2>
                                <p>By proceeding you accept our terms and Conditions.</p>
                                <a class="button button2" href="#">Next</a>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
            <div class="single_slider d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6 col-md-6">
                            <div class="slider_content">
                                <img src="{% static 'installation/assets/images/3.png' %}" alt="">
                            </div>
                        </div>
                        <div class="col-xl-6 col-md-6 mt-md-0 mt-3 position-relative">

                            <div class="load-overlay content-overlay" style="display:none;">
                               <div class="overlay">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="loader-container">
                                                <div class="innerloader">
                                                    <svg class="circular" viewBox="25 25 50 50">
                                                    <circle class="path" cx="50" cy="50" r="10" fill="none" stroke-width="2" stroke-miterlimit="10"/>
                                                    </svg>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                               </div>
                            </div> 
                            <div class="slider_content hider">
                                <h1>Now ready</h1>
                                <h2>Begin installation</h2>
                                <p>Please follow the following steps to install site.</p>
                                <a class="button start_installation" href="{% url 'installation start' %}">start</a>
                            </div>
                        </div>                      
                    </div>
                </div>
            </div>
             
        </div>
    </section>
    <!--slider area end-->
<script src="{% static 'installation/assets/js/jquery-3.5.1.min.js' %}"></script> 
<script src="{% static 'installation/assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'installation/assets/js/plugins.js' %}"></script>
<script src="{% static 'installation/assets/js/main.js' %}"></script>
<script src="{% static 'installation/assets/js/custom.js' %}"></script>
<script>
   
    /*start_installation*/
    $(document).on('click','.start_installation',function(e)
    {
        e.preventDefault();
        var el=$(this),
        url=el.attr('href');
        $('.content-overlay').find('.loader-container').html(`<div class="innerloader">
                                                                <svg class="circular" viewBox="25 25 50 50">
                                                                <circle class="path" cx="50" cy="50" r="10" fill="none" stroke-width="2" stroke-miterlimit="10"/>
                                                                </svg>
                                                            </div>`);
        $.ajax(
        {
            url:url,
            context:this,
            dataType:'html',
            beforeSend:function()
            {
                $('.hider').html('');
                $('.content-overlay').show();
            },
            success:function(results)
            {
                $('.content-overlay').hide();
                $('.hider').html(results)

            },
            error:function(error)
            {
                $('.content-overlay').find('.loader-container').html('<span class="text-danger">'+error.status+':'+error.statusText+'</span> | <a class="text-info start_installation" href="'+url+'">retry</a>')
            }
        })
    });
   
</script>
</body>
</html>

templates/installation/installation_user_register.html
<div class="account-content position-relative">
    <div class="load-overlay store-overlay" style="display:none;background-color:rgba(255,255,255,0.7);">
        <span class="overlay-close btn-remove" title="close overlay"><i class="fa fa-close"></i></span>
        <div class="overlay">
              <div class="row">
                  <div class="col-12">
                      <div class="loader-container">
                      <div class="innerloader">
                          <svg class="circular" viewBox="25 25 50 50">
                          <circle class="path" cx="50" cy="50" r="10" fill="none" stroke-width="2" stroke-miterlimit="10"/>
                          </svg>
                      </div>
                      </div>
                  </div>
              </div>
        </div>
      </div>
    <form data-url="{% url 'installation start' %}" class="installationForm" novalidate>
        <div class="progress-process">
            <div class="step first_step">
                <p>info</p>
                <div class="bullet">
                  <span>1</span>
                </div>
                <div class="check fas fa-check"></div>
            </div>
            <div class="step second_step">
                <p>Site config</p>
                <div class="bullet">
                    <span>2</span>
                </div>
                <div class="check fas fa-check"></div>
            </div>
            <div class="step third_step">
                <p>Finish</p>
                <div class="bullet">
                    <span>3</span>
                </div>
                <div class="check fas fa-check"></div>
            </div>
        </div>
        <div class="row first_step">
            <div class="col-12">
                {% csrf_token %}
            </div>
            <div class="col-md-6 col-12">
                <div class="form-group single-acc-field">
                    <label for="id_first_name" class="float-left">First name</label>
                    {{userform.first_name}}
                    <div class="feedback text-left"></div>
                </div>  
            </div>
            <div class="col-md-6 col-12">
                <div class="form-group single-acc-field">
                    <label for="id_last_name" class="float-left">Last name</label>
                    {{userform.last_name}}
                    <div class="feedback text-left"></div>
                </div>  
            </div>
            <div class="col-12">
                <div class="form-group single-acc-field">
                    <label for="id_email" class="float-left">Email</label>
                    {{userform.email}}
                    <div class="feedback text-left"></div> 
                </div>
            </div>
             <div class="col-12">
                <div class="form-group single-acc-field">
                    <label for="id_username" class="float-left">Username</label>
                    {{userform.username}}
                    <div class="feedback text-left"></div> 
                </div>
             </div>
             <div class="col-12 text-md-right text-center">
                <div class="single-acc-field">
                    {% if count <= 0 %}
                     <button type="button" class="nextBtn">next</button>
                     {% else %}
                     <button type="button" class="btn btn-secondary nextBtn" disabled>disabled</button>
                     {% endif %}
                </div>
             </div>
        </div>

        <div class="row second_step" style="display:none;">
            <div class="col-12">
                <div class="form-group single-acc-field">
                    <label for="id_phone_0"  class="text-left">Phone</label>
                    <div class="row">
                        <div class="col-12">
                            {{extendedForm.phone}}
                        </div>
                        <div class="col-12">
                            <div class="feedback text-left"></div> 
                        </div>
                    </div>
                </div>  
            </div>
            <div class="col-12">
                <div class="form-group single-acc-field">
                    <label for="id_site_name" class="float-left">Site name</label>
                    {{siteconstantform.site_name}}
                    <div class="feedback text-left"></div> 
                </div>
            </div>
             <div class="col-12">
                <div class="form-group single-acc-field">
                    <label for="id_site_url" class="float-left">Site ur</label>
                    <input name="site_url" value="{{request.scheme}}://{{request.get_host}}" aria-label="site_url" placeholder="eg example.com" type="url" class="form-control"  style="text-transform:lowercase;" readonly>
                    <div class="feedback text-left"></div> 
                </div>
             </div>
             <div class="col-12 text-md-right text-center">
                <div class="single-acc-field">
                    <button type="button" class="prevBtn">prev</button>
                    <button type="button" class="nextBtn">next</button>
                </div>
             </div>
        </div>

        <div class="row third_step" style="display:none;">
            <div class="col-12">
                <div class="form-group single-acc-field">
                    <label for="id_password1" class="float-left">Password</label>
                    {{userform.password1}}
                    <div class="feedback text-left"></div> 
                </div>  
            </div>
            <div class="col-12">
                <div class="form-group single-acc-field">
                    <label for="id_password2" class="float-left">Confirm Password</label>
                    {{userform.password2}}
                    <div class="feedback text-left"></div> 
                </div>
            </div>
            <div class="col-12">
                <div class="form-group single-acc-field boxes">
                    {{main.main}}
                    <label for="id_main">Main superuser</label>
                </div>
            </div>
             <div class="col-12 text-md-right text-center">
                <div class="single-acc-field">
                    <button type="button" class="prevBtn">prev</button>
                    <button type="submit" class="finishBtn">finish</button>
                </div>
             </div>
        </div>
    </form>
</div>
</div>